language: python
install:
  - pip install -r tests/requirements.txt
python:
  - 2.7
  - 3.3
  - 3.4
before_script:
  - git config --global user.email travis@ci
  - git config --global user.name Travis
script:
  - nosetests --with-coverage
after_success:
  - coveralls
